'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:2.0.50727.3603
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict Off
Option Explicit On

Imports System
Imports System.ComponentModel
Imports System.Data
Imports System.Diagnostics
Imports System.Web.Services
Imports System.Web.Services.Protocols
Imports System.Xml.Serialization
Imports System.Configuration

'
'This source code was auto-generated by wsdl, Version=2.0.50727.1432.
'
Namespace Seguridad.UsrSeguridad.Dat_Opciones


    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.1432"), _
     System.Diagnostics.DebuggerStepThroughAttribute(), _
     System.ComponentModel.DesignerCategoryAttribute("code"), _
     System.Web.Services.WebServiceBindingAttribute(Name:="Dat_OpcionesSoap", [Namespace]:="http://www.prosoft.cr/")> _
    Partial Public Class Dat_Opciones
        Inherits System.Web.Services.Protocols.SoapHttpClientProtocol

        Private AgregarBDOperationCompleted As System.Threading.SendOrPostCallback

        Private BorrarBDOperationCompleted As System.Threading.SendOrPostCallback

        Private ModificarBDOperationCompleted As System.Threading.SendOrPostCallback

        Private TraerRegistroBDOperationCompleted As System.Threading.SendOrPostCallback

        Private TraerListaPorOpcPadreBDOperationCompleted As System.Threading.SendOrPostCallback

        Private TraerListaTotalBDOperationCompleted As System.Threading.SendOrPostCallback

        Private TraerListaTotalPorRolBDOperationCompleted As System.Threading.SendOrPostCallback

        Private ListaCamposOperationCompleted As System.Threading.SendOrPostCallback

        Private NumeroOpcionMayorOperationCompleted As System.Threading.SendOrPostCallback

        Private NumeroOpcionMayorOrdenOperationCompleted As System.Threading.SendOrPostCallback

        '''<remarks/>
        Public Sub New()
            MyBase.New()
            Me.Url = ConfigurationManager.AppSettings(Constantes.ServidorDatos) + "UsrSeguridad/Dat_Opciones.asmx"
        End Sub

        '''<remarks/>
        Public Event AgregarBDCompleted As AgregarBDCompletedEventHandler

        '''<remarks/>
        Public Event BorrarBDCompleted As BorrarBDCompletedEventHandler

        '''<remarks/>
        Public Event ModificarBDCompleted As ModificarBDCompletedEventHandler

        '''<remarks/>
        Public Event TraerRegistroBDCompleted As TraerRegistroBDCompletedEventHandler

        '''<remarks/>
        Public Event TraerListaPorOpcPadreBDCompleted As TraerListaPorOpcPadreBDCompletedEventHandler

        '''<remarks/>
        Public Event TraerListaTotalBDCompleted As TraerListaTotalBDCompletedEventHandler

        '''<remarks/>
        Public Event TraerListaTotalPorRolBDCompleted As TraerListaTotalPorRolBDCompletedEventHandler

        '''<remarks/>
        Public Event ListaCamposCompleted As ListaCamposCompletedEventHandler

        '''<remarks/>
        Public Event NumeroOpcionMayorCompleted As NumeroOpcionMayorCompletedEventHandler

        '''<remarks/>
        Public Event NumeroOpcionMayorOrdenCompleted As NumeroOpcionMayorOrdenCompletedEventHandler

        '''<remarks/>
        <System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://www.prosoft.cr/AgregarBD", RequestNamespace:="http://www.prosoft.cr/", ResponseNamespace:="http://www.prosoft.cr/", Use:=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle:=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)> _
        Public Sub AgregarBD(ByVal varCodigoSistema As Double, ByVal varCodigoModulo As Double, ByVal varCodigoOpcion As Double, ByVal varNombre As String, ByVal varNombreFisico As String, ByVal varEstado As String, ByVal varCodigoOpcionPadre As Double, ByVal varCodigoTipoOpcion As Double, ByVal varOrden As Double)
            Me.Invoke("AgregarBD", New Object() {varCodigoSistema, varCodigoModulo, varCodigoOpcion, varNombre, varNombreFisico, varEstado, varCodigoOpcionPadre, varCodigoTipoOpcion, varOrden})
        End Sub

        '''<remarks/>
        Public Function BeginAgregarBD(ByVal varCodigoSistema As Double, ByVal varCodigoModulo As Double, ByVal varCodigoOpcion As Double, ByVal varNombre As String, ByVal varNombreFisico As String, ByVal varEstado As String, ByVal varCodigoOpcionPadre As Double, ByVal varCodigoTipoOpcion As Double, ByVal varOrden As Double, ByVal callback As System.AsyncCallback, ByVal asyncState As Object) As System.IAsyncResult
            Return Me.BeginInvoke("AgregarBD", New Object() {varCodigoSistema, varCodigoModulo, varCodigoOpcion, varNombre, varNombreFisico, varEstado, varCodigoOpcionPadre, varCodigoTipoOpcion, varOrden}, callback, asyncState)
        End Function

        '''<remarks/>
        Public Sub EndAgregarBD(ByVal asyncResult As System.IAsyncResult)
            Me.EndInvoke(asyncResult)
        End Sub

        '''<remarks/>
        Public Overloads Sub AgregarBDAsync(ByVal varCodigoSistema As Double, ByVal varCodigoModulo As Double, ByVal varCodigoOpcion As Double, ByVal varNombre As String, ByVal varNombreFisico As String, ByVal varEstado As String, ByVal varCodigoOpcionPadre As Double, ByVal varCodigoTipoOpcion As Double, ByVal varOrden As Double)
            Me.AgregarBDAsync(varCodigoSistema, varCodigoModulo, varCodigoOpcion, varNombre, varNombreFisico, varEstado, varCodigoOpcionPadre, varCodigoTipoOpcion, varOrden, Nothing)
        End Sub

        '''<remarks/>
        Public Overloads Sub AgregarBDAsync(ByVal varCodigoSistema As Double, ByVal varCodigoModulo As Double, ByVal varCodigoOpcion As Double, ByVal varNombre As String, ByVal varNombreFisico As String, ByVal varEstado As String, ByVal varCodigoOpcionPadre As Double, ByVal varCodigoTipoOpcion As Double, ByVal varOrden As Double, ByVal userState As Object)
            If (Me.AgregarBDOperationCompleted Is Nothing) Then
                Me.AgregarBDOperationCompleted = AddressOf Me.OnAgregarBDOperationCompleted
            End If
            Me.InvokeAsync("AgregarBD", New Object() {varCodigoSistema, varCodigoModulo, varCodigoOpcion, varNombre, varNombreFisico, varEstado, varCodigoOpcionPadre, varCodigoTipoOpcion, varOrden}, Me.AgregarBDOperationCompleted, userState)
        End Sub

        Private Sub OnAgregarBDOperationCompleted(ByVal arg As Object)
            If (Not (Me.AgregarBDCompletedEvent) Is Nothing) Then
                Dim invokeArgs As System.Web.Services.Protocols.InvokeCompletedEventArgs = CType(arg, System.Web.Services.Protocols.InvokeCompletedEventArgs)
                RaiseEvent AgregarBDCompleted(Me, New System.ComponentModel.AsyncCompletedEventArgs(invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState))
            End If
        End Sub

        '''<remarks/>
        <System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://www.prosoft.cr/BorrarBD", RequestNamespace:="http://www.prosoft.cr/", ResponseNamespace:="http://www.prosoft.cr/", Use:=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle:=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)> _
        Public Sub BorrarBD(ByVal varCodigoSistema As Double, ByVal varCodigoModulo As Double, ByVal varCodigoOpcion As Double)
            Me.Invoke("BorrarBD", New Object() {varCodigoSistema, varCodigoModulo, varCodigoOpcion})
        End Sub

        '''<remarks/>
        Public Function BeginBorrarBD(ByVal varCodigoSistema As Double, ByVal varCodigoModulo As Double, ByVal varCodigoOpcion As Double, ByVal callback As System.AsyncCallback, ByVal asyncState As Object) As System.IAsyncResult
            Return Me.BeginInvoke("BorrarBD", New Object() {varCodigoSistema, varCodigoModulo, varCodigoOpcion}, callback, asyncState)
        End Function

        '''<remarks/>
        Public Sub EndBorrarBD(ByVal asyncResult As System.IAsyncResult)
            Me.EndInvoke(asyncResult)
        End Sub

        '''<remarks/>
        Public Overloads Sub BorrarBDAsync(ByVal varCodigoSistema As Double, ByVal varCodigoModulo As Double, ByVal varCodigoOpcion As Double)
            Me.BorrarBDAsync(varCodigoSistema, varCodigoModulo, varCodigoOpcion, Nothing)
        End Sub

        '''<remarks/>
        Public Overloads Sub BorrarBDAsync(ByVal varCodigoSistema As Double, ByVal varCodigoModulo As Double, ByVal varCodigoOpcion As Double, ByVal userState As Object)
            If (Me.BorrarBDOperationCompleted Is Nothing) Then
                Me.BorrarBDOperationCompleted = AddressOf Me.OnBorrarBDOperationCompleted
            End If
            Me.InvokeAsync("BorrarBD", New Object() {varCodigoSistema, varCodigoModulo, varCodigoOpcion}, Me.BorrarBDOperationCompleted, userState)
        End Sub

        Private Sub OnBorrarBDOperationCompleted(ByVal arg As Object)
            If (Not (Me.BorrarBDCompletedEvent) Is Nothing) Then
                Dim invokeArgs As System.Web.Services.Protocols.InvokeCompletedEventArgs = CType(arg, System.Web.Services.Protocols.InvokeCompletedEventArgs)
                RaiseEvent BorrarBDCompleted(Me, New System.ComponentModel.AsyncCompletedEventArgs(invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState))
            End If
        End Sub

        '''<remarks/>
        <System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://www.prosoft.cr/ModificarBD", RequestNamespace:="http://www.prosoft.cr/", ResponseNamespace:="http://www.prosoft.cr/", Use:=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle:=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)> _
        Public Sub ModificarBD(ByVal varCodigoSistema As Double, ByVal varCodigoModulo As Double, ByVal varCodigoOpcion As Double, ByVal varNombre As String, ByVal varNombreFisico As String, ByVal varEstado As String, ByVal varCodigoOpcionPadre As Double, ByVal varCodigoTipoOpcion As Double)
            Me.Invoke("ModificarBD", New Object() {varCodigoSistema, varCodigoModulo, varCodigoOpcion, varNombre, varNombreFisico, varEstado, varCodigoOpcionPadre, varCodigoTipoOpcion})
        End Sub

        '''<remarks/>
        Public Function BeginModificarBD(ByVal varCodigoSistema As Double, ByVal varCodigoModulo As Double, ByVal varCodigoOpcion As Double, ByVal varNombre As String, ByVal varNombreFisico As String, ByVal varEstado As String, ByVal varCodigoOpcionPadre As Double, ByVal varCodigoTipoOpcion As Double, ByVal callback As System.AsyncCallback, ByVal asyncState As Object) As System.IAsyncResult
            Return Me.BeginInvoke("ModificarBD", New Object() {varCodigoSistema, varCodigoModulo, varCodigoOpcion, varNombre, varNombreFisico, varEstado, varCodigoOpcionPadre, varCodigoTipoOpcion}, callback, asyncState)
        End Function

        '''<remarks/>
        Public Sub EndModificarBD(ByVal asyncResult As System.IAsyncResult)
            Me.EndInvoke(asyncResult)
        End Sub

        '''<remarks/>
        Public Overloads Sub ModificarBDAsync(ByVal varCodigoSistema As Double, ByVal varCodigoModulo As Double, ByVal varCodigoOpcion As Double, ByVal varNombre As String, ByVal varNombreFisico As String, ByVal varEstado As String, ByVal varCodigoOpcionPadre As Double, ByVal varCodigoTipoOpcion As Double)
            Me.ModificarBDAsync(varCodigoSistema, varCodigoModulo, varCodigoOpcion, varNombre, varNombreFisico, varEstado, varCodigoOpcionPadre, varCodigoTipoOpcion, Nothing)
        End Sub

        '''<remarks/>
        Public Overloads Sub ModificarBDAsync(ByVal varCodigoSistema As Double, ByVal varCodigoModulo As Double, ByVal varCodigoOpcion As Double, ByVal varNombre As String, ByVal varNombreFisico As String, ByVal varEstado As String, ByVal varCodigoOpcionPadre As Double, ByVal varCodigoTipoOpcion As Double, ByVal userState As Object)
            If (Me.ModificarBDOperationCompleted Is Nothing) Then
                Me.ModificarBDOperationCompleted = AddressOf Me.OnModificarBDOperationCompleted
            End If
            Me.InvokeAsync("ModificarBD", New Object() {varCodigoSistema, varCodigoModulo, varCodigoOpcion, varNombre, varNombreFisico, varEstado, varCodigoOpcionPadre, varCodigoTipoOpcion}, Me.ModificarBDOperationCompleted, userState)
        End Sub

        Private Sub OnModificarBDOperationCompleted(ByVal arg As Object)
            If (Not (Me.ModificarBDCompletedEvent) Is Nothing) Then
                Dim invokeArgs As System.Web.Services.Protocols.InvokeCompletedEventArgs = CType(arg, System.Web.Services.Protocols.InvokeCompletedEventArgs)
                RaiseEvent ModificarBDCompleted(Me, New System.ComponentModel.AsyncCompletedEventArgs(invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState))
            End If
        End Sub

        '''<remarks/>
        <System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://www.prosoft.cr/TraerRegistroBD", RequestNamespace:="http://www.prosoft.cr/", ResponseNamespace:="http://www.prosoft.cr/", Use:=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle:=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)> _
        Public Sub TraerRegistroBD(ByVal varCodigoSistema As Double, ByVal varCodigoModulo As Double, ByVal varCodigoOpcion As Double, ByRef varNombre As String, ByRef varNombreFisico As String, ByRef varEstado As String, ByRef varCodigoOpcionPadre As Double, ByRef varCodigoTipoOpcion As Double, ByRef varOrden As Double)
            Dim results() As Object = Me.Invoke("TraerRegistroBD", New Object() {varCodigoSistema, varCodigoModulo, varCodigoOpcion, varNombre, varNombreFisico, varEstado, varCodigoOpcionPadre, varCodigoTipoOpcion, varOrden})
            varNombre = CType(results(0), String)
            varNombreFisico = CType(results(1), String)
            varEstado = CType(results(2), String)
            varCodigoOpcionPadre = CType(results(3), Double)
            varCodigoTipoOpcion = CType(results(4), Double)
            varOrden = CType(results(5), Double)
        End Sub

        '''<remarks/>
        Public Function BeginTraerRegistroBD(ByVal varCodigoSistema As Double, ByVal varCodigoModulo As Double, ByVal varCodigoOpcion As Double, ByVal varNombre As String, ByVal varNombreFisico As String, ByVal varEstado As String, ByVal varCodigoOpcionPadre As Double, ByVal varCodigoTipoOpcion As Double, ByVal varOrden As Double, ByVal callback As System.AsyncCallback, ByVal asyncState As Object) As System.IAsyncResult
            Return Me.BeginInvoke("TraerRegistroBD", New Object() {varCodigoSistema, varCodigoModulo, varCodigoOpcion, varNombre, varNombreFisico, varEstado, varCodigoOpcionPadre, varCodigoTipoOpcion, varOrden}, callback, asyncState)
        End Function

        '''<remarks/>
        Public Sub EndTraerRegistroBD(ByVal asyncResult As System.IAsyncResult, ByRef varNombre As String, ByRef varNombreFisico As String, ByRef varEstado As String, ByRef varCodigoOpcionPadre As Double, ByRef varCodigoTipoOpcion As Double, ByRef varOrden As Double)
            Dim results() As Object = Me.EndInvoke(asyncResult)
            varNombre = CType(results(0), String)
            varNombreFisico = CType(results(1), String)
            varEstado = CType(results(2), String)
            varCodigoOpcionPadre = CType(results(3), Double)
            varCodigoTipoOpcion = CType(results(4), Double)
            varOrden = CType(results(5), Double)
        End Sub

        '''<remarks/>
        Public Overloads Sub TraerRegistroBDAsync(ByVal varCodigoSistema As Double, ByVal varCodigoModulo As Double, ByVal varCodigoOpcion As Double, ByVal varNombre As String, ByVal varNombreFisico As String, ByVal varEstado As String, ByVal varCodigoOpcionPadre As Double, ByVal varCodigoTipoOpcion As Double, ByVal varOrden As Double)
            Me.TraerRegistroBDAsync(varCodigoSistema, varCodigoModulo, varCodigoOpcion, varNombre, varNombreFisico, varEstado, varCodigoOpcionPadre, varCodigoTipoOpcion, varOrden, Nothing)
        End Sub

        '''<remarks/>
        Public Overloads Sub TraerRegistroBDAsync(ByVal varCodigoSistema As Double, ByVal varCodigoModulo As Double, ByVal varCodigoOpcion As Double, ByVal varNombre As String, ByVal varNombreFisico As String, ByVal varEstado As String, ByVal varCodigoOpcionPadre As Double, ByVal varCodigoTipoOpcion As Double, ByVal varOrden As Double, ByVal userState As Object)
            If (Me.TraerRegistroBDOperationCompleted Is Nothing) Then
                Me.TraerRegistroBDOperationCompleted = AddressOf Me.OnTraerRegistroBDOperationCompleted
            End If
            Me.InvokeAsync("TraerRegistroBD", New Object() {varCodigoSistema, varCodigoModulo, varCodigoOpcion, varNombre, varNombreFisico, varEstado, varCodigoOpcionPadre, varCodigoTipoOpcion, varOrden}, Me.TraerRegistroBDOperationCompleted, userState)
        End Sub

        Private Sub OnTraerRegistroBDOperationCompleted(ByVal arg As Object)
            If (Not (Me.TraerRegistroBDCompletedEvent) Is Nothing) Then
                Dim invokeArgs As System.Web.Services.Protocols.InvokeCompletedEventArgs = CType(arg, System.Web.Services.Protocols.InvokeCompletedEventArgs)
                RaiseEvent TraerRegistroBDCompleted(Me, New TraerRegistroBDCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState))
            End If
        End Sub

        '''<remarks/>
        <System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://www.prosoft.cr/TraerListaPorOpcPadreBD", RequestNamespace:="http://www.prosoft.cr/", ResponseNamespace:="http://www.prosoft.cr/", Use:=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle:=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)> _
        Public Function TraerListaPorOpcPadreBD(ByVal varCodigoSistema As Double, ByVal varCodigoModulo As Double, ByVal varCodigoOpcionPadre As Double, ByVal MaxRegistros As Integer) As System.Data.DataSet
            Dim results() As Object = Me.Invoke("TraerListaPorOpcPadreBD", New Object() {varCodigoSistema, varCodigoModulo, varCodigoOpcionPadre, MaxRegistros})
            Return CType(results(0), System.Data.DataSet)
        End Function

        '''<remarks/>
        Public Function BeginTraerListaPorOpcPadreBD(ByVal varCodigoSistema As Double, ByVal varCodigoModulo As Double, ByVal varCodigoOpcionPadre As Double, ByVal MaxRegistros As Integer, ByVal callback As System.AsyncCallback, ByVal asyncState As Object) As System.IAsyncResult
            Return Me.BeginInvoke("TraerListaPorOpcPadreBD", New Object() {varCodigoSistema, varCodigoModulo, varCodigoOpcionPadre, MaxRegistros}, callback, asyncState)
        End Function

        '''<remarks/>
        Public Function EndTraerListaPorOpcPadreBD(ByVal asyncResult As System.IAsyncResult) As System.Data.DataSet
            Dim results() As Object = Me.EndInvoke(asyncResult)
            Return CType(results(0), System.Data.DataSet)
        End Function

        '''<remarks/>
        Public Overloads Sub TraerListaPorOpcPadreBDAsync(ByVal varCodigoSistema As Double, ByVal varCodigoModulo As Double, ByVal varCodigoOpcionPadre As Double, ByVal MaxRegistros As Integer)
            Me.TraerListaPorOpcPadreBDAsync(varCodigoSistema, varCodigoModulo, varCodigoOpcionPadre, MaxRegistros, Nothing)
        End Sub

        '''<remarks/>
        Public Overloads Sub TraerListaPorOpcPadreBDAsync(ByVal varCodigoSistema As Double, ByVal varCodigoModulo As Double, ByVal varCodigoOpcionPadre As Double, ByVal MaxRegistros As Integer, ByVal userState As Object)
            If (Me.TraerListaPorOpcPadreBDOperationCompleted Is Nothing) Then
                Me.TraerListaPorOpcPadreBDOperationCompleted = AddressOf Me.OnTraerListaPorOpcPadreBDOperationCompleted
            End If
            Me.InvokeAsync("TraerListaPorOpcPadreBD", New Object() {varCodigoSistema, varCodigoModulo, varCodigoOpcionPadre, MaxRegistros}, Me.TraerListaPorOpcPadreBDOperationCompleted, userState)
        End Sub

        Private Sub OnTraerListaPorOpcPadreBDOperationCompleted(ByVal arg As Object)
            If (Not (Me.TraerListaPorOpcPadreBDCompletedEvent) Is Nothing) Then
                Dim invokeArgs As System.Web.Services.Protocols.InvokeCompletedEventArgs = CType(arg, System.Web.Services.Protocols.InvokeCompletedEventArgs)
                RaiseEvent TraerListaPorOpcPadreBDCompleted(Me, New TraerListaPorOpcPadreBDCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState))
            End If
        End Sub

        '''<remarks/>
        <System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://www.prosoft.cr/TraerListaTotalBD", RequestNamespace:="http://www.prosoft.cr/", ResponseNamespace:="http://www.prosoft.cr/", Use:=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle:=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)> _
        Public Function TraerListaTotalBD(ByVal ListaCondiciones As clsListaCondiciones, ByVal MaxRegistros As Integer) As System.Data.DataSet
            Dim results() As Object = Me.Invoke("TraerListaTotalBD", New Object() {ListaCondiciones, MaxRegistros})
            Return CType(results(0), System.Data.DataSet)
        End Function

        '''<remarks/>
        Public Function BeginTraerListaTotalBD(ByVal ListaCondiciones As clsListaCondiciones, ByVal MaxRegistros As Integer, ByVal callback As System.AsyncCallback, ByVal asyncState As Object) As System.IAsyncResult
            Return Me.BeginInvoke("TraerListaTotalBD", New Object() {ListaCondiciones, MaxRegistros}, callback, asyncState)
        End Function

        '''<remarks/>
        Public Function EndTraerListaTotalBD(ByVal asyncResult As System.IAsyncResult) As System.Data.DataSet
            Dim results() As Object = Me.EndInvoke(asyncResult)
            Return CType(results(0), System.Data.DataSet)
        End Function

        '''<remarks/>
        Public Overloads Sub TraerListaTotalBDAsync(ByVal ListaCondiciones As clsListaCondiciones, ByVal MaxRegistros As Integer)
            Me.TraerListaTotalBDAsync(ListaCondiciones, MaxRegistros, Nothing)
        End Sub

        '''<remarks/>
        Public Overloads Sub TraerListaTotalBDAsync(ByVal ListaCondiciones As clsListaCondiciones, ByVal MaxRegistros As Integer, ByVal userState As Object)
            If (Me.TraerListaTotalBDOperationCompleted Is Nothing) Then
                Me.TraerListaTotalBDOperationCompleted = AddressOf Me.OnTraerListaTotalBDOperationCompleted
            End If
            Me.InvokeAsync("TraerListaTotalBD", New Object() {ListaCondiciones, MaxRegistros}, Me.TraerListaTotalBDOperationCompleted, userState)
        End Sub

        Private Sub OnTraerListaTotalBDOperationCompleted(ByVal arg As Object)
            If (Not (Me.TraerListaTotalBDCompletedEvent) Is Nothing) Then
                Dim invokeArgs As System.Web.Services.Protocols.InvokeCompletedEventArgs = CType(arg, System.Web.Services.Protocols.InvokeCompletedEventArgs)
                RaiseEvent TraerListaTotalBDCompleted(Me, New TraerListaTotalBDCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState))
            End If
        End Sub

        '''<remarks/>
        <System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://www.prosoft.cr/TraerListaTotalPorRolBD", RequestNamespace:="http://www.prosoft.cr/", ResponseNamespace:="http://www.prosoft.cr/", Use:=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle:=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)> _
        Public Function TraerListaTotalPorRolBD(ByVal varCodigoRol As Double, ByVal ListaCondiciones As clsListaCondiciones, ByVal MaxRegistros As Integer) As System.Data.DataSet
            Dim results() As Object = Me.Invoke("TraerListaTotalPorRolBD", New Object() {varCodigoRol, ListaCondiciones, MaxRegistros})
            Return CType(results(0), System.Data.DataSet)
        End Function

        '''<remarks/>
        Public Function BeginTraerListaTotalPorRolBD(ByVal varCodigoRol As Double, ByVal ListaCondiciones As clsListaCondiciones, ByVal MaxRegistros As Integer, ByVal callback As System.AsyncCallback, ByVal asyncState As Object) As System.IAsyncResult
            Return Me.BeginInvoke("TraerListaTotalPorRolBD", New Object() {varCodigoRol, ListaCondiciones, MaxRegistros}, callback, asyncState)
        End Function

        '''<remarks/>
        Public Function EndTraerListaTotalPorRolBD(ByVal asyncResult As System.IAsyncResult) As System.Data.DataSet
            Dim results() As Object = Me.EndInvoke(asyncResult)
            Return CType(results(0), System.Data.DataSet)
        End Function

        '''<remarks/>
        Public Overloads Sub TraerListaTotalPorRolBDAsync(ByVal varCodigoRol As Double, ByVal ListaCondiciones As clsListaCondiciones, ByVal MaxRegistros As Integer)
            Me.TraerListaTotalPorRolBDAsync(varCodigoRol, ListaCondiciones, MaxRegistros, Nothing)
        End Sub

        '''<remarks/>
        Public Overloads Sub TraerListaTotalPorRolBDAsync(ByVal varCodigoRol As Double, ByVal ListaCondiciones As clsListaCondiciones, ByVal MaxRegistros As Integer, ByVal userState As Object)
            If (Me.TraerListaTotalPorRolBDOperationCompleted Is Nothing) Then
                Me.TraerListaTotalPorRolBDOperationCompleted = AddressOf Me.OnTraerListaTotalPorRolBDOperationCompleted
            End If
            Me.InvokeAsync("TraerListaTotalPorRolBD", New Object() {varCodigoRol, ListaCondiciones, MaxRegistros}, Me.TraerListaTotalPorRolBDOperationCompleted, userState)
        End Sub

        Private Sub OnTraerListaTotalPorRolBDOperationCompleted(ByVal arg As Object)
            If (Not (Me.TraerListaTotalPorRolBDCompletedEvent) Is Nothing) Then
                Dim invokeArgs As System.Web.Services.Protocols.InvokeCompletedEventArgs = CType(arg, System.Web.Services.Protocols.InvokeCompletedEventArgs)
                RaiseEvent TraerListaTotalPorRolBDCompleted(Me, New TraerListaTotalPorRolBDCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState))
            End If
        End Sub

        '''<remarks/>
        <System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://www.prosoft.cr/ListaCampos", RequestNamespace:="http://www.prosoft.cr/", ResponseNamespace:="http://www.prosoft.cr/", Use:=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle:=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)> _
        Public Function ListaCampos() As clsListaCampos
            Dim results() As Object = Me.Invoke("ListaCampos", New Object(-1) {})
            Return CType(results(0), clsListaCampos)
        End Function

        '''<remarks/>
        Public Function BeginListaCampos(ByVal callback As System.AsyncCallback, ByVal asyncState As Object) As System.IAsyncResult
            Return Me.BeginInvoke("ListaCampos", New Object(-1) {}, callback, asyncState)
        End Function

        '''<remarks/>
        Public Function EndListaCampos(ByVal asyncResult As System.IAsyncResult) As clsListaCampos
            Dim results() As Object = Me.EndInvoke(asyncResult)
            Return CType(results(0), clsListaCampos)
        End Function

        '''<remarks/>
        Public Overloads Sub ListaCamposAsync()
            Me.ListaCamposAsync(Nothing)
        End Sub

        '''<remarks/>
        Public Overloads Sub ListaCamposAsync(ByVal userState As Object)
            If (Me.ListaCamposOperationCompleted Is Nothing) Then
                Me.ListaCamposOperationCompleted = AddressOf Me.OnListaCamposOperationCompleted
            End If
            Me.InvokeAsync("ListaCampos", New Object(-1) {}, Me.ListaCamposOperationCompleted, userState)
        End Sub

        Private Sub OnListaCamposOperationCompleted(ByVal arg As Object)
            If (Not (Me.ListaCamposCompletedEvent) Is Nothing) Then
                Dim invokeArgs As System.Web.Services.Protocols.InvokeCompletedEventArgs = CType(arg, System.Web.Services.Protocols.InvokeCompletedEventArgs)
                RaiseEvent ListaCamposCompleted(Me, New ListaCamposCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState))
            End If
        End Sub

        '''<remarks/>
        <System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://www.prosoft.cr/NumeroOpcionMayor", RequestNamespace:="http://www.prosoft.cr/", ResponseNamespace:="http://www.prosoft.cr/", Use:=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle:=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)> _
        Public Function NumeroOpcionMayor(ByVal pCodigoSistema As Double, ByVal pCodigoModulo As Double) As Double
            Dim results() As Object = Me.Invoke("NumeroOpcionMayor", New Object() {pCodigoSistema, pCodigoModulo})
            Return CType(results(0), Double)
        End Function

        '''<remarks/>
        Public Function BeginNumeroOpcionMayor(ByVal pCodigoSistema As Double, ByVal pCodigoModulo As Double, ByVal callback As System.AsyncCallback, ByVal asyncState As Object) As System.IAsyncResult
            Return Me.BeginInvoke("NumeroOpcionMayor", New Object() {pCodigoSistema, pCodigoModulo}, callback, asyncState)
        End Function

        '''<remarks/>
        Public Function EndNumeroOpcionMayor(ByVal asyncResult As System.IAsyncResult) As Double
            Dim results() As Object = Me.EndInvoke(asyncResult)
            Return CType(results(0), Double)
        End Function

        '''<remarks/>
        Public Overloads Sub NumeroOpcionMayorAsync(ByVal pCodigoSistema As Double, ByVal pCodigoModulo As Double)
            Me.NumeroOpcionMayorAsync(pCodigoSistema, pCodigoModulo, Nothing)
        End Sub

        '''<remarks/>
        Public Overloads Sub NumeroOpcionMayorAsync(ByVal pCodigoSistema As Double, ByVal pCodigoModulo As Double, ByVal userState As Object)
            If (Me.NumeroOpcionMayorOperationCompleted Is Nothing) Then
                Me.NumeroOpcionMayorOperationCompleted = AddressOf Me.OnNumeroOpcionMayorOperationCompleted
            End If
            Me.InvokeAsync("NumeroOpcionMayor", New Object() {pCodigoSistema, pCodigoModulo}, Me.NumeroOpcionMayorOperationCompleted, userState)
        End Sub

        Private Sub OnNumeroOpcionMayorOperationCompleted(ByVal arg As Object)
            If (Not (Me.NumeroOpcionMayorCompletedEvent) Is Nothing) Then
                Dim invokeArgs As System.Web.Services.Protocols.InvokeCompletedEventArgs = CType(arg, System.Web.Services.Protocols.InvokeCompletedEventArgs)
                RaiseEvent NumeroOpcionMayorCompleted(Me, New NumeroOpcionMayorCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState))
            End If
        End Sub

        '''<remarks/>
        <System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://www.prosoft.cr/NumeroOpcionMayorOrden", RequestNamespace:="http://www.prosoft.cr/", ResponseNamespace:="http://www.prosoft.cr/", Use:=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle:=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)> _
        Public Function NumeroOpcionMayorOrden(ByVal pCodigoSistema As Double, ByVal pCodigoModulo As Double) As Double
            Dim results() As Object = Me.Invoke("NumeroOpcionMayorOrden", New Object() {pCodigoSistema, pCodigoModulo})
            Return CType(results(0), Double)
        End Function

        '''<remarks/>
        Public Function BeginNumeroOpcionMayorOrden(ByVal pCodigoSistema As Double, ByVal pCodigoModulo As Double, ByVal callback As System.AsyncCallback, ByVal asyncState As Object) As System.IAsyncResult
            Return Me.BeginInvoke("NumeroOpcionMayorOrden", New Object() {pCodigoSistema, pCodigoModulo}, callback, asyncState)
        End Function

        '''<remarks/>
        Public Function EndNumeroOpcionMayorOrden(ByVal asyncResult As System.IAsyncResult) As Double
            Dim results() As Object = Me.EndInvoke(asyncResult)
            Return CType(results(0), Double)
        End Function

        '''<remarks/>
        Public Overloads Sub NumeroOpcionMayorOrdenAsync(ByVal pCodigoSistema As Double, ByVal pCodigoModulo As Double)
            Me.NumeroOpcionMayorOrdenAsync(pCodigoSistema, pCodigoModulo, Nothing)
        End Sub

        '''<remarks/>
        Public Overloads Sub NumeroOpcionMayorOrdenAsync(ByVal pCodigoSistema As Double, ByVal pCodigoModulo As Double, ByVal userState As Object)
            If (Me.NumeroOpcionMayorOrdenOperationCompleted Is Nothing) Then
                Me.NumeroOpcionMayorOrdenOperationCompleted = AddressOf Me.OnNumeroOpcionMayorOrdenOperationCompleted
            End If
            Me.InvokeAsync("NumeroOpcionMayorOrden", New Object() {pCodigoSistema, pCodigoModulo}, Me.NumeroOpcionMayorOrdenOperationCompleted, userState)
        End Sub

        Private Sub OnNumeroOpcionMayorOrdenOperationCompleted(ByVal arg As Object)
            If (Not (Me.NumeroOpcionMayorOrdenCompletedEvent) Is Nothing) Then
                Dim invokeArgs As System.Web.Services.Protocols.InvokeCompletedEventArgs = CType(arg, System.Web.Services.Protocols.InvokeCompletedEventArgs)
                RaiseEvent NumeroOpcionMayorOrdenCompleted(Me, New NumeroOpcionMayorOrdenCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState))
            End If
        End Sub

        '''<remarks/>
        Public Shadows Sub CancelAsync(ByVal userState As Object)
            MyBase.CancelAsync(userState)
        End Sub
    End Class

    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.1432"), _
     System.SerializableAttribute(), _
     System.Diagnostics.DebuggerStepThroughAttribute(), _
     System.ComponentModel.DesignerCategoryAttribute("code"), _
     System.Xml.Serialization.XmlTypeAttribute([Namespace]:="http://www.prosoft.cr/")> _
    Partial Public Class clsListaCampos
    End Class

    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.1432")> _
    Public Delegate Sub AgregarBDCompletedEventHandler(ByVal sender As Object, ByVal e As System.ComponentModel.AsyncCompletedEventArgs)

    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.1432")> _
    Public Delegate Sub BorrarBDCompletedEventHandler(ByVal sender As Object, ByVal e As System.ComponentModel.AsyncCompletedEventArgs)

    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.1432")> _
    Public Delegate Sub ModificarBDCompletedEventHandler(ByVal sender As Object, ByVal e As System.ComponentModel.AsyncCompletedEventArgs)

    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.1432")> _
    Public Delegate Sub TraerRegistroBDCompletedEventHandler(ByVal sender As Object, ByVal e As TraerRegistroBDCompletedEventArgs)

    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.1432"), _
     System.Diagnostics.DebuggerStepThroughAttribute(), _
     System.ComponentModel.DesignerCategoryAttribute("code")> _
    Partial Public Class TraerRegistroBDCompletedEventArgs
        Inherits System.ComponentModel.AsyncCompletedEventArgs

        Private results() As Object

        Friend Sub New(ByVal results() As Object, ByVal exception As System.Exception, ByVal cancelled As Boolean, ByVal userState As Object)
            MyBase.New(exception, cancelled, userState)
            Me.results = results
        End Sub

        '''<remarks/>
        Public ReadOnly Property varNombre() As String
            Get
                Me.RaiseExceptionIfNecessary()
                Return CType(Me.results(0), String)
            End Get
        End Property

        '''<remarks/>
        Public ReadOnly Property varNombreFisico() As String
            Get
                Me.RaiseExceptionIfNecessary()
                Return CType(Me.results(1), String)
            End Get
        End Property

        '''<remarks/>
        Public ReadOnly Property varEstado() As String
            Get
                Me.RaiseExceptionIfNecessary()
                Return CType(Me.results(2), String)
            End Get
        End Property

        '''<remarks/>
        Public ReadOnly Property varCodigoOpcionPadre() As Double
            Get
                Me.RaiseExceptionIfNecessary()
                Return CType(Me.results(3), Double)
            End Get
        End Property

        '''<remarks/>
        Public ReadOnly Property varCodigoTipoOpcion() As Double
            Get
                Me.RaiseExceptionIfNecessary()
                Return CType(Me.results(4), Double)
            End Get
        End Property

        '''<remarks/>
        Public ReadOnly Property varOrden() As Double
            Get
                Me.RaiseExceptionIfNecessary()
                Return CType(Me.results(5), Double)
            End Get
        End Property
    End Class

    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.1432")> _
    Public Delegate Sub TraerListaPorOpcPadreBDCompletedEventHandler(ByVal sender As Object, ByVal e As TraerListaPorOpcPadreBDCompletedEventArgs)

    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.1432"), _
     System.Diagnostics.DebuggerStepThroughAttribute(), _
     System.ComponentModel.DesignerCategoryAttribute("code")> _
    Partial Public Class TraerListaPorOpcPadreBDCompletedEventArgs
        Inherits System.ComponentModel.AsyncCompletedEventArgs

        Private results() As Object

        Friend Sub New(ByVal results() As Object, ByVal exception As System.Exception, ByVal cancelled As Boolean, ByVal userState As Object)
            MyBase.New(exception, cancelled, userState)
            Me.results = results
        End Sub

        '''<remarks/>
        Public ReadOnly Property Result() As System.Data.DataSet
            Get
                Me.RaiseExceptionIfNecessary()
                Return CType(Me.results(0), System.Data.DataSet)
            End Get
        End Property
    End Class

    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.1432")> _
    Public Delegate Sub TraerListaTotalBDCompletedEventHandler(ByVal sender As Object, ByVal e As TraerListaTotalBDCompletedEventArgs)

    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.1432"), _
     System.Diagnostics.DebuggerStepThroughAttribute(), _
     System.ComponentModel.DesignerCategoryAttribute("code")> _
    Partial Public Class TraerListaTotalBDCompletedEventArgs
        Inherits System.ComponentModel.AsyncCompletedEventArgs

        Private results() As Object

        Friend Sub New(ByVal results() As Object, ByVal exception As System.Exception, ByVal cancelled As Boolean, ByVal userState As Object)
            MyBase.New(exception, cancelled, userState)
            Me.results = results
        End Sub

        '''<remarks/>
        Public ReadOnly Property Result() As System.Data.DataSet
            Get
                Me.RaiseExceptionIfNecessary()
                Return CType(Me.results(0), System.Data.DataSet)
            End Get
        End Property
    End Class

    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.1432")> _
    Public Delegate Sub TraerListaTotalPorRolBDCompletedEventHandler(ByVal sender As Object, ByVal e As TraerListaTotalPorRolBDCompletedEventArgs)

    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.1432"), _
     System.Diagnostics.DebuggerStepThroughAttribute(), _
     System.ComponentModel.DesignerCategoryAttribute("code")> _
    Partial Public Class TraerListaTotalPorRolBDCompletedEventArgs
        Inherits System.ComponentModel.AsyncCompletedEventArgs

        Private results() As Object

        Friend Sub New(ByVal results() As Object, ByVal exception As System.Exception, ByVal cancelled As Boolean, ByVal userState As Object)
            MyBase.New(exception, cancelled, userState)
            Me.results = results
        End Sub

        '''<remarks/>
        Public ReadOnly Property Result() As System.Data.DataSet
            Get
                Me.RaiseExceptionIfNecessary()
                Return CType(Me.results(0), System.Data.DataSet)
            End Get
        End Property
    End Class

    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.1432")> _
    Public Delegate Sub ListaCamposCompletedEventHandler(ByVal sender As Object, ByVal e As ListaCamposCompletedEventArgs)

    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.1432"), _
     System.Diagnostics.DebuggerStepThroughAttribute(), _
     System.ComponentModel.DesignerCategoryAttribute("code")> _
    Partial Public Class ListaCamposCompletedEventArgs
        Inherits System.ComponentModel.AsyncCompletedEventArgs

        Private results() As Object

        Friend Sub New(ByVal results() As Object, ByVal exception As System.Exception, ByVal cancelled As Boolean, ByVal userState As Object)
            MyBase.New(exception, cancelled, userState)
            Me.results = results
        End Sub

        '''<remarks/>
        Public ReadOnly Property Result() As clsListaCampos
            Get
                Me.RaiseExceptionIfNecessary()
                Return CType(Me.results(0), clsListaCampos)
            End Get
        End Property
    End Class

    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.1432")> _
    Public Delegate Sub NumeroOpcionMayorCompletedEventHandler(ByVal sender As Object, ByVal e As NumeroOpcionMayorCompletedEventArgs)

    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.1432"), _
     System.Diagnostics.DebuggerStepThroughAttribute(), _
     System.ComponentModel.DesignerCategoryAttribute("code")> _
    Partial Public Class NumeroOpcionMayorCompletedEventArgs
        Inherits System.ComponentModel.AsyncCompletedEventArgs

        Private results() As Object

        Friend Sub New(ByVal results() As Object, ByVal exception As System.Exception, ByVal cancelled As Boolean, ByVal userState As Object)
            MyBase.New(exception, cancelled, userState)
            Me.results = results
        End Sub

        '''<remarks/>
        Public ReadOnly Property Result() As Double
            Get
                Me.RaiseExceptionIfNecessary()
                Return CType(Me.results(0), Double)
            End Get
        End Property
    End Class

    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.1432")> _
    Public Delegate Sub NumeroOpcionMayorOrdenCompletedEventHandler(ByVal sender As Object, ByVal e As NumeroOpcionMayorOrdenCompletedEventArgs)

    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.1432"), _
     System.Diagnostics.DebuggerStepThroughAttribute(), _
     System.ComponentModel.DesignerCategoryAttribute("code")> _
    Partial Public Class NumeroOpcionMayorOrdenCompletedEventArgs
        Inherits System.ComponentModel.AsyncCompletedEventArgs

        Private results() As Object

        Friend Sub New(ByVal results() As Object, ByVal exception As System.Exception, ByVal cancelled As Boolean, ByVal userState As Object)
            MyBase.New(exception, cancelled, userState)
            Me.results = results
        End Sub

        '''<remarks/>
        Public ReadOnly Property Result() As Double
            Get
                Me.RaiseExceptionIfNecessary()
                Return CType(Me.results(0), Double)
            End Get
        End Property
    End Class
End Namespace